// Central icon adapter: re-exports Material Design icons with Lucide-compatible names.
// All components import from '@/lib/icons' instead of 'lucide-react'.

import { IconType } from 'react-icons';

// Backward-compatible type alias for components that reference LucideIcon
export type LucideIcon = IconType;
// Also export as LucideProps-compatible (some files use this)
export type LucideProps = React.SVGAttributes<SVGElement> & { size?: number | string };

// ─── Icon re-exports (Lucide name → Material Design icon) ──────────────────

export {
  MdError as AlertCircle,
  MdWarning as AlertTriangle,
  MdArrowBack as ArrowLeft,
  MdArrowDownward as ArrowDown,
  MdArrowForward as ArrowRight,
  MdArrowUpward as ArrowUp,
  MdGraphicEq as AudioWaveform,
  MdBarChart as BarChart3,
  MdNotifications as Bell,
  MdFormatBold as Bold,
  MdPsychology as Brain,
  MdWork as Briefcase,
  MdBugReport as Bug,
  MdBusiness as Building2,
  MdCalendarToday as Calendar,
  MdCalendarToday as CalendarIcon,
  MdCameraAlt as Camera,
  MdCampaign as Megaphone,
  MdCheck as Check,
  MdCheckCircle as CheckCircle,
  MdCheckCircle as CheckCircle2,
  MdExpandMore as ChevronDown,
  MdChevronLeft as ChevronLeft,
  MdChevronRight as ChevronRight,
  MdExpandLess as ChevronUp,
  MdUnfoldMore as ChevronsUpDown,
  MdFiberManualRecord as Circle,
  MdFiberManualRecord as Dot,
  MdViewColumn as Columns3,
  MdContentCopy as Copy,
  MdStars as Crown,
  MdStorage as Database,
  MdDownload as Download,
  MdOutlineEdit as Edit,
  MdOutlineEdit as Edit2,
  MdOpenInNew as ExternalLink,
  MdVisibility as Eye,
  MdVisibilityOff as EyeOff,
  MdOutlineInsertChart as FileBarChart,
  MdFindInPage as FileSearch,
  MdTableChart as FileSpreadsheet,
  MdDescription as FileText,
  MdFilterList as Filter,
  MdLanguage as Globe,
  MdGridOn as Grid3X3,
  MdDragIndicator as GripVertical,
  MdFavorite as Heart,
  MdHelp as HelpCircle,
  MdHistory as History,
  MdImage as Image,
  MdHideImage as ImageOff,
  MdAddPhotoAlternate as ImagePlus,
  MdInfoOutline as Info,
  MdFormatItalic as Italic,
  MdLayers as Layers,
  MdDashboard as LayoutDashboard,
  MdViewSidebar as LayoutPanelLeft,
  MdOutlineHelpOutline as LifeBuoy,
  MdLightbulb as Lightbulb,
  MdFormatListBulleted as List,
  MdFormatListNumbered as ListOrdered,
  MdSync as Loader2,
  MdLock as Lock,
  MdLocationOn as MapPin,
  MdFullscreen as Maximize2,
  MdMenu as Menu,
  MdChatBubble as MessageCircle,
  MdOutlineChatBubbleOutline as MessageSquare,
  MdAddComment as MessageSquarePlus,
  MdSms as MessageSquareText,
  MdMonitor as Monitor,
  MdDarkMode as Moon,
  MdMoreHoriz as MoreHorizontal,
  MdMoreVert as MoreVertical,
  MdNavigation as Navigation,
  MdMenuOpen as PanelLeft,
  MdAttachFile as Paperclip,
  MdOutlineEdit as Pencil,
  MdPerson as User,
  MdPlayArrow as Play,
  MdAdd as Plus,
  MdRefresh as RefreshCcw,
  MdRefresh as RefreshCw,
  MdOutlineUndo as RotateCcw,
  MdRedo as RotateCw,
  MdSave as Save,
  MdSearch as Search,
  MdSend as Send,
  MdSettings as Settings,
  MdTune as Settings2,
  MdShare as Share2,
  MdShield as Shield,
  MdGppBad as ShieldAlert,
  MdOutlineVerifiedUser as ShieldCheck,
  MdTune as SlidersHorizontal,
  MdAutoAwesome as Sparkles,
  MdStop as Square,
  MdLightMode as Sun,
  MdThumbDown as ThumbsDown,
  MdThumbUp as ThumbsUp,
  MdDelete as Trash2,
  MdTrendingDown as TrendingDown,
  MdOutlineTrendingUp as TrendingUp,
  MdFormatUnderlined as Underline,
  MdUpload as Upload,
  MdOutlineManageAccounts as UserCog,
  MdPersonAdd as UserPlus,
  MdOutlinePeopleOutline as Users,
  MdBuild as Wrench,
  MdClose as X,
} from 'react-icons/md';
